version: 2

models:
- name: trips
  description: "The Citibike trips"
  columns:
    - name: bike_id
      description: "Bike id"
    - name: birth_year
      description: "Rider birth year"
    - name: end_station_id
      description: "Station id where trip ended"
    - name: end_station_latitude
      description: "Latitude of the station where the trip ended"
    - name: end_station_longitude
      description: "Longitude of the station where the trip ended"
    - name: end_station_name
      description: "Name of station where the trip ended"
    - name: gender
      description: "Rider gender"
    - name: membership_type
      description: "Membership type of that rider signed up"
    - name: start_station_id
      description: "Station id where trip started"
    - name: start_station_latitude
      description: "Latitude of the station where the trip started"
    - name: start_station_longitude
      description: "Longitude of the station where the trip started"
    - name: start_station_name
      description: "Name of the station where the trip started"
    - name: start_time
      description: "Time when the trip started"
    - name: stop_time
      description: "Time when the trip ended"
    - name: trip_duration
      description: "Duration of the trip"
    - name: usertype
      description: "User type"

- name: riders
  description: "The Citibike riders"
  columns:
    - name: json
      description: "Serialized value of riders"

- name: expanded_riders
  description: "The Citibike riders with expanded attributes"
  columns:
    - name: bikeid
      description: "Bike id"
    - name: bike_type
      description: "Bike type"
    - name: end_station_id
      description: "Station id where trip ended"
    - name: endtime
      description: "Time when the trip ended"
    - name: rider_dob
      description: "Rider date of birth"
    - name: rider_email
      description: "Rider email"
    - name: rider_first_name
      description: "Rider first name"
    - name: rider_last_name
      description: "Rider last name"
    - name: gender
      description: "Rider gender"
    - name: member_type
      description: "Rider member type"
    - name: payment_type
      description: "Payment type"
    - name: payment_phone_num
      description: "Phone number used to pay"
    - name: payment_phone_type
      description: "Phone platform"
    - name: cc_num
      description: "Credit card number"
    - name: cc_type
      description: "Card issuer"
