version: 2

models:
  - name: trips
    description: "The Citibike trips"
    columns:
      - name: bike_id
        description: "The bike id"
      - name: gender
        description: "Gender"

  - name: trips_view
    description: "View of trips"
    columns:
      - name: bike_id
        description: "The bike id"
