name: 'citibike'
version: '1.0.0'
config-version: 2

# Match the profile in global dbt config.
profile: 'citibike'

# Project folders.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  citibike:
    raw:
      +materialized: view
