version: '3.8'

services:
  postgres:
    image: postgres:10.23-alpine
    container_name: postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    healthcheck:
      test: 'pg_isready -U postgres'
    networks:
      - simulator_internal
  simulator:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: simulator
    environment:
      # Since postgres and simulator are in the same network, we use host=postgres port=5432.
      DS_DSN: 'host=postgres port=5432 user=pguser password=password dbname=db sslmode=disable'
      AWS_ACCESS_KEY_ID: 'XXX'
      AWS_SECRET_ACCESS_KEY: 'YYY'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - simulator_internal

networks:
  simulator_internal:
