version: '3.8'

services:
  postgres:
    image: postgres:10.23-alpine
    container_name: postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
networks:
  simulator_internal:
